python ProjectAERIS.py Test_Suite/Test_Cases/fda001.txt Postprocessing/IntermediateFiles/fda001.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/fda007.txt Postprocessing/IntermediateFiles/fda007.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/fda008.txt Postprocessing/IntermediateFiles/fda008.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/fda009.txt Postprocessing/IntermediateFiles/fda009.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/fda010.txt Postprocessing/IntermediateFiles/fda010.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen011.txt Postprocessing/IntermediateFiles/gen011.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen012.txt Postprocessing/IntermediateFiles/gen012.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen013.txt Postprocessing/IntermediateFiles/gen013.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen014.txt Postprocessing/IntermediateFiles/gen014.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen015.txt Postprocessing/IntermediateFiles/gen015.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen016.txt Postprocessing/IntermediateFiles/gen016.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen017.txt Postprocessing/IntermediateFiles/gen017.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen018.txt Postprocessing/IntermediateFiles/gen018.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen019.txt Postprocessing/IntermediateFiles/gen019.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen020.txt Postprocessing/IntermediateFiles/gen020.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen021.txt Postprocessing/IntermediateFiles/gen021.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen022.txt Postprocessing/IntermediateFiles/gen022.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen023.txt Postprocessing/IntermediateFiles/gen023.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen024.txt Postprocessing/IntermediateFiles/gen024.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen025.txt Postprocessing/IntermediateFiles/gen025.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen026.txt Postprocessing/IntermediateFiles/gen026.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen027.txt Postprocessing/IntermediateFiles/gen027.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen028.txt Postprocessing/IntermediateFiles/gen028.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen029.txt Postprocessing/IntermediateFiles/gen029.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen030.txt Postprocessing/IntermediateFiles/gen030.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen031.txt Postprocessing/IntermediateFiles/gen031.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen032.txt Postprocessing/IntermediateFiles/gen032.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen033.txt Postprocessing/IntermediateFiles/gen033.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen034.txt Postprocessing/IntermediateFiles/gen034.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen035.txt Postprocessing/IntermediateFiles/gen035.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen036.txt Postprocessing/IntermediateFiles/gen036.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen037.txt Postprocessing/IntermediateFiles/gen037.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen038.txt Postprocessing/IntermediateFiles/gen038.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen039.txt Postprocessing/IntermediateFiles/gen039.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen040.txt Postprocessing/IntermediateFiles/gen040.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen041.txt Postprocessing/IntermediateFiles/gen041.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen042.txt Postprocessing/IntermediateFiles/gen042.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen043.txt Postprocessing/IntermediateFiles/gen043.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen044.txt Postprocessing/IntermediateFiles/gen044.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen045.txt Postprocessing/IntermediateFiles/gen045.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen046.txt Postprocessing/IntermediateFiles/gen046.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen047.txt Postprocessing/IntermediateFiles/gen047.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen048.txt Postprocessing/IntermediateFiles/gen048.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen049.txt Postprocessing/IntermediateFiles/gen049.xml Resources/config.json
python ProjectAERIS.py Test_Suite/Test_Cases/gen050.txt Postprocessing/IntermediateFiles/gen050.xml Resources/config.json
